[package]
name = "app_ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
path = "src/app_ui.rs"

[dependencies]
assets = { path = "../assets" }
dock = { path = "../dock" }
gpui.workspace = true
gpui_macros.workspace = true
gpui-component.workspace = true
keymap = { path = "../keymap" }
notifications = { path = "../notifications" }
status_bar = { path = "../status_bar" }
theme = { path = "../theme" }
ui = { path = "../ui" }
workspace = { path = "../workspace" }
