[package]
name = "welcome"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
path = "src/welcome.rs"

[dependencies]
actions = { path = "../actions" }
commands = { path = "../commands" }
module = { path = "../module" }
panel = { path = "../panel" }
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true
