[package]
name = "workspace"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
path = "src/workspace.rs"

[dependencies]
actions = { path = "../actions" }
command_palette = { path = "../command_palette" }
dock = { path = "../dock" }
panel = { path = "../panel" }
